[build]
target = "thumbv7m-none-eabi"


[profile.dev]
debug = true


[profile.release]
opt-level = 0   
overflow-checks = false
debug = false

[target.thumbv7m-none-eabi]
# uncomment ONE of these options option to make `cargo run` start a GDB session
# which option to pick depends on your system
runner = "arm-none-eabi-gdb -q -x openocd.gdb"
# # runner = "gdb-multiarch -q -x openocd.gdb"
# # runner = "gdb -q -x openocd.gdb"

rustflags = ["-C", "link-arg=-Tlink.x"]